export const CLINIC_TYPES = [
  { value: 'diagnostika_markazi', label: "Diagnostika markazi", icon: '🔬' },
  { value: 'poliklinika',         label: 'Poliklinika',          icon: '🏥' },
  { value: 'kasalxona',           label: 'Kasalxona',            icon: '🏨' },
  { value: 'ixtisoslashgan_markaz', label: "Ixtisoslashgan markaz", icon: '🎯' },
  { value: 'tish_klinikasi',      label: 'Tish klinikasi',       icon: '🦷' },
  { value: 'sanatoriya',          label: 'Sanatoriya',           icon: '🏖️' },
];

export const UZBEKISTAN_REGIONS = [
  { id: 'tashkent_city',    name: "Toshkent shahri" },
  { id: 'tashkent_region',  name: "Toshkent viloyati" },
  { id: 'andijan',          name: "Andijon viloyati" },
  { id: 'fergana',          name: "Farg'ona viloyati" },
  { id: 'namangan',         name: 'Namangan viloyati' },
  { id: 'samarkand',        name: 'Samarqand viloyati' },
  { id: 'bukhara',          name: 'Buxoro viloyati' },
  { id: 'navoi',            name: "Navoiy viloyati" },
  { id: 'kashkadarya',      name: "Qashqadaryo viloyati" },
  { id: 'surkhandarya',     name: 'Surxondaryo viloyati' },
  { id: 'jizzakh',          name: 'Jizzax viloyati' },
  { id: 'syrdarya',         name: "Sirdaryo viloyati" },
  { id: 'khorezm',          name: 'Xorazm viloyati' },
  { id: 'karakalpakstan',   name: "Qoraqalpog'iston Respublikasi" },
];

export const DISTRICTS_BY_REGION = {
  tashkent_city: [
    { id: 'bektemir',     name: 'Bektemir' },
    { id: 'chilanzar',    name: 'Chilonzor' },
    { id: 'mirzo_ulugbek',name: "Mirzo Ulug'bek" },
    { id: 'mirobod',      name: 'Mirobod' },
    { id: 'olmazor',      name: 'Olmazor' },
    { id: 'sergeli',      name: 'Sergeli' },
    { id: 'shayhontohur', name: "Shayxontohur" },
    { id: 'uchtepa',      name: 'Uchtepa' },
    { id: 'yakkasaray',   name: 'Yakkasaroy' },
    { id: 'yunusobod',    name: 'Yunusobod' },
    { id: 'yashnobod',    name: 'Yashnobod' },
  ],
  tashkent_region: [
    { id: 'angren',       name: 'Angren' },
    { id: 'bekobod',      name: 'Bekobod' },
    { id: 'bostonliq',    name: "Bo'stonliq" },
    { id: 'chinoz',       name: 'Chinoz' },
    { id: 'ohangaron',    name: 'Ohangaron' },
    { id: 'oqqurgon',     name: "Oqqo'rg'on" },
    { id: 'parkent',      name: 'Parkent' },
    { id: 'piskent',      name: 'Piskent' },
    { id: 'qibray',       name: 'Qibray' },
    { id: 'yangiyo\'l',   name: "Yangiyo'l" },
    { id: 'zangiota',     name: 'Zangiota' },
  ],
  andijan: [
    { id: 'andijan_city', name: 'Andijon shahri' },
    { id: 'asaka',        name: 'Asaka' },
    { id: 'baliqchi',     name: "Baliqchi" },
    { id: 'buloqboshi',   name: "Buloqboshi" },
    { id: 'izboskan',     name: 'Izboskan' },
    { id: 'jalaquduq',    name: "Jalaquduq" },
    { id: 'marhamat',     name: 'Marhamat' },
    { id: 'oltinko\'l',   name: "Oltinko'l" },
    { id: 'paxtaobod',    name: 'Paxtaobod' },
    { id: 'shahrixon',    name: 'Shahrixon' },
    { id: 'ulugʼnor',     name: "Ulug'nor" },
  ],
  fergana: [
    { id: 'fergana_city', name: "Farg'ona shahri" },
    { id: 'beshariq',     name: 'Beshariq' },
    { id: 'buvayda',      name: 'Buvayda' },
    { id: 'dangʼara',     name: "Dang'ara" },
    { id: 'furqat',       name: 'Furqat' },
    { id: 'kuhiston',     name: "Qo'qon shahri" },
    { id: 'margilan',     name: "Marg'ilon shahri" },
    { id: 'oltiariq',     name: 'Oltiariq' },
    { id: 'uchko\'prik',  name: "Uchko'prik" },
    { id: 'yozyovon',     name: 'Yozyovon' },
  ],
  namangan: [
    { id: 'namangan_city', name: 'Namangan shahri' },
    { id: 'chortoq',      name: "Chortoq" },
    { id: 'chust',        name: 'Chust' },
    { id: 'kosonsoy',     name: 'Kosonsoy' },
    { id: 'mingbuloq',    name: 'Mingbuloq' },
    { id: 'norin',        name: 'Norin' },
    { id: 'pop',          name: 'Pop' },
    { id: 'to\'raqo\'rgon', name: "To'raqo'rg'on" },
    { id: 'uychi',        name: 'Uychi' },
    { id: 'yangiqo\'rgon', name: "Yangiqo'rg'on" },
  ],
  samarkand: [
    { id: 'samarkand_city', name: 'Samarqand shahri' },
    { id: 'bulung\'ur',   name: "Bulung'ur" },
    { id: 'ishtixon',     name: 'Ishtixon' },
    { id: 'jomboy',       name: 'Jomboy' },
    { id: 'kattaqo\'rgon', name: "Kattaqo'rg'on" },
    { id: 'narpay',       name: 'Narpay' },
    { id: 'nurobod',      name: 'Nurobod' },
    { id: 'pastdarg\'om', name: "Pastdarg'om" },
    { id: 'payariq',      name: 'Payariq' },
    { id: 'urgut',        name: 'Urgut' },
  ],
  bukhara: [
    { id: 'bukhara_city', name: 'Buxoro shahri' },
    { id: 'gijduvon',     name: 'Gijduvon' },
    { id: 'jondor',       name: 'Jondor' },
    { id: 'kogon',        name: "Ko'g'on" },
    { id: 'kuyimozor',    name: "Quyimozor" },
    { id: 'peshku',       name: 'Peshku' },
    { id: 'romitan',      name: 'Romitan' },
    { id: 'shofirkon',    name: 'Shofirkon' },
    { id: 'vobkent',      name: 'Vobkent' },
  ],
  navoi: [
    { id: 'navoi_city',   name: 'Navoiy shahri' },
    { id: 'karmana',      name: 'Karmana' },
    { id: 'konimex',      name: 'Konimex' },
    { id: 'navbahor',     name: 'Navbahor' },
    { id: 'nurota',       name: 'Nurota' },
    { id: 'qiziltepa',    name: 'Qiziltepa' },
    { id: 'tomdi',        name: 'Tomdi' },
    { id: 'uchquduq',     name: 'Uchquduq' },
    { id: 'zarafshon',    name: 'Zarafshon' },
  ],
  kashkadarya: [
    { id: 'qarshi_city',  name: 'Qarshi shahri' },
    { id: 'chiroqchi',    name: 'Chiroqchi' },
    { id: 'dehqonobod',   name: 'Dehqonobod' },
    { id: 'guzor',        name: 'G\'uzor' },
    { id: 'kasbi',        name: 'Kasbi' },
    { id: 'kitob',        name: 'Kitob' },
    { id: 'koson',        name: 'Koson' },
    { id: 'muborak',      name: 'Muborak' },
    { id: 'nishon',       name: 'Nishon' },
    { id: 'shahrisabz',   name: 'Shahrisabz' },
  ],
  surkhandarya: [
    { id: 'termez_city',  name: 'Termiz shahri' },
    { id: 'angor',        name: 'Angor' },
    { id: 'bandixon',     name: 'Bandixon' },
    { id: 'boysun',       name: 'Boysun' },
    { id: 'denov',        name: 'Denov' },
    { id: 'muzrabot',     name: 'Muzrabot' },
    { id: 'oltinsoy',     name: 'Oltinsoy' },
    { id: 'qumqo\'rgon',  name: "Qumqo'rg'on" },
    { id: 'sariosiyo',    name: 'Sariosiyo' },
    { id: 'sherobod',     name: 'Sherobod' },
    { id: 'uzun',         name: 'Uzun' },
  ],
  jizzakh: [
    { id: 'jizzakh_city', name: 'Jizzax shahri' },
    { id: 'arnasoy',      name: 'Arnasoy' },
    { id: 'bakhmal',      name: 'Baxmal' },
    { id: 'dustlik',      name: 'Dustlik' },
    { id: 'forish',       name: 'Forish' },
    { id: 'gallaorol',    name: 'G\'allaorol' },
    { id: 'paxtakor',     name: 'Paxtakor' },
    { id: 'sharof_rashidov', name: "Sharof Rashidov" },
    { id: 'yangiobod',    name: 'Yangiobod' },
    { id: 'zafarobod',    name: 'Zafarobod' },
    { id: 'zomin',        name: 'Zomin' },
  ],
  syrdarya: [
    { id: 'guliston_city', name: 'Guliston shahri' },
    { id: 'boyovut',      name: 'Boyovut' },
    { id: 'mirzaobod',    name: 'Mirzaobod' },
    { id: 'oqoltin',      name: 'Oqoltin' },
    { id: 'sardoba',      name: 'Sardoba' },
    { id: 'sayxunobod',   name: 'Sayxunobod' },
    { id: 'shirin',       name: 'Shirin shahri' },
    { id: 'xovos',        name: 'Xovos' },
  ],
  khorezm: [
    { id: 'urgench_city', name: 'Urganch shahri' },
    { id: 'bog\'ot',      name: "Bog'ot" },
    { id: 'gurlan',       name: 'Gurlan' },
    { id: 'hazorasp',     name: 'Hazorasp' },
    { id: 'khiva_city',   name: 'Xiva shahri' },
    { id: 'kushkupir',    name: 'Kushkupir' },
    { id: 'shavot',       name: 'Shavot' },
    { id: 'yangiariq',    name: 'Yangiariq' },
    { id: 'yangibozor',   name: 'Yangibozor' },
  ],
  karakalpakstan: [
    { id: 'nukus_city',   name: 'Nukus shahri' },
    { id: 'amudarya',     name: 'Amudaryo' },
    { id: 'beruniy',      name: 'Beruniy' },
    { id: 'chimboy',      name: 'Chimboy' },
    { id: 'ellikqala',    name: "Ellikqal'a" },
    { id: 'kegeyli',      name: "Kegeyli" },
    { id: 'mo\'ynoq',     name: "Mo'ynoq" },
    { id: 'qanliko\'l',   name: "Qaniko'l" },
    { id: 'shumanay',     name: 'Shumanay' },
    { id: 'takhtakupir',  name: 'Taxtako\'pir' },
    { id: 'turtkul',      name: "To'rtko'l" },
    { id: 'xo\'jayli',    name: "Xo'jayli" },
  ],
};

export const POSITIONS = [
  { value: 'direktor',       label: 'Direktor' },
  { value: 'bosh_vrach',     label: 'Bosh vrach' },
  { value: 'tibbiy_direktor', label: 'Tibbiy direktor' },
  { value: 'manager',        label: 'Manager' },
  { value: 'boshqa',         label: 'Boshqa' },
];

export const LEGAL_FORMS = [
  { value: 'mchj',           label: 'MChJ (Mas\'uliyati Cheklangan Jamiyat)' },
  { value: 'aj',             label: 'AJ (Aksiyadorlik Jamiyati)' },
  { value: 'xk',             label: 'XK (Xususiy Korxona)' },
  { value: 'yakka',          label: 'Yakka tartibdagi tadbirkor' },
  { value: 'davlat',         label: "Davlat muassasasi" },
  { value: 'boshqa',         label: 'Boshqa' },
];

export const BANKS = [
  { value: 'hamkorbank',     label: 'Hamkorbank' },
  { value: 'kapitalbank',    label: 'Kapitalbank' },
  { value: 'ipoteka',        label: 'Ipoteka bank' },
  { value: 'xalq',          label: 'Xalq banki' },
  { value: 'asaka',          label: 'Asaka bank' },
  { value: 'uzpromstroybank', label: 'Uzpromstroybank' },
  { value: 'agrobank',       label: 'Agrobank' },
  { value: 'aloqabank',      label: 'Aloqabank' },
  { value: 'savdogarbank',   label: 'Savdogar bank' },
  { value: 'boshqa',         label: 'Boshqa' },
];

export const PAYMENT_METHODS = [
  { value: 'CLICK',  label: 'Click', icon: '📱' },
  { value: 'PAYME',  label: 'Payme', icon: '💳' },
  { value: 'UZCARD', label: 'Uzcard', icon: '💳' },
  { value: 'HUMO',   label: 'Humo', icon: '💳' },
  { value: 'CASH',   label: "Naqd pul", icon: '💵' },
  { value: 'BANK',   label: "Bank o'tkazmasi", icon: '🏦' },
];

export const DAYS_OF_WEEK = [
  { key: 'monday',    label: 'Dushanba', short: 'Du' },
  { key: 'tuesday',   label: 'Seshanba',  short: 'Se' },
  { key: 'wednesday', label: 'Chorshanba', short: 'Ch' },
  { key: 'thursday',  label: 'Payshanba', short: 'Pa' },
  { key: 'friday',    label: 'Juma',      short: 'Ju' },
  { key: 'saturday',  label: 'Shanba',    short: 'Sh' },
  { key: 'sunday',    label: 'Yakshanba', short: 'Ya' },
];

export const DEFAULT_WORKING_HOURS = {
  monday:    { isOpen: true,  openTime: '08:00', closeTime: '18:00', isAroundClock: false },
  tuesday:   { isOpen: true,  openTime: '08:00', closeTime: '18:00', isAroundClock: false },
  wednesday: { isOpen: true,  openTime: '08:00', closeTime: '18:00', isAroundClock: false },
  thursday:  { isOpen: true,  openTime: '08:00', closeTime: '18:00', isAroundClock: false },
  friday:    { isOpen: true,  openTime: '08:00', closeTime: '18:00', isAroundClock: false },
  saturday:  { isOpen: true,  openTime: '09:00', closeTime: '15:00', isAroundClock: false },
  sunday:    { isOpen: false, openTime: '09:00', closeTime: '15:00', isAroundClock: false },
};

export const STEPS = [
  { id: 1, key: 'basicInfo',     label: "Asosiy Ma'lumotlar",  icon: '🏥' },
  { id: 2, key: 'location',      label: 'Joylashuv',            icon: '📍' },
  { id: 3, key: 'contacts',      label: 'Aloqa Ma\'lumotlari', icon: '📞' },
  { id: 4, key: 'workingHours',  label: 'Ish Vaqtlari',        icon: '🕐' },
  { id: 5, key: 'services',      label: 'Xizmatlar',            icon: '💊' },
  { id: 6, key: 'adminPerson',   label: "Mas'ul Shaxs",        icon: '👤' },
  { id: 7, key: 'documents',     label: 'Hujjatlar',            icon: '📄' },
  { id: 8, key: 'payment',       label: "To'lov Ma'lumotlari", icon: '🏦' },
];

export const SERVICES_BY_CLINIC_TYPE = {
  diagnostika_markazi: ['Laboratoriya tahlillari', 'UZI tekshiruvi', "Rentgen (X-Ray)", 'KT skanerlash', 'MRI skanerlash', "EKG/EEG", 'Endoskopiya', 'Checkup paketlari'],
  poliklinika: ['Terapevt qabuli', 'Pediatr qabuli', 'Kardiolog qabuli', 'Nevropatolog qabuli', 'Ginekolog qabuli', 'Laboratoriya tahlillari', 'UZI tekshiruvi', 'Rentgen (X-Ray)'],
  kasalxona: ['Umumiy xirurgiya', "Laparoskopik amaliyot", "Ortopedik amaliyot", "Kardiologik amaliyot", 'Statsionar davolash', 'Reanimatsiya', 'Laboratoriya tahlillari', 'UZI tekshiruvi'],
  ixtisoslashgan_markaz: ["Ixtisoslashgan konsultatsiya", "Ixtisoslashgan amaliyot", 'Laboratoriya tahlillari', 'UZI tekshiruvi', 'Statsionar davolash', 'Reabilitatsiya'],
  tish_klinikasi: ["Terapevtik stomatologiya", 'Xirurgik stomatologiya', 'Ortodontiya', 'Protezlash', "Implantatsiya", "Tish oqlash", 'Bolalar stomatologiyasi', "Rentgen panorama"],
  sanatoriya: ["Balneologik muolajalar", "Fizioterapiya", 'Massaj', 'Gryo terapiya', "Reabilitatsiya", 'Dieta ovqatlanish', "Psixologik yordam", 'Sport zali'],
};
